/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JPanel;


/**
 *
 * @author Isaelsantos
 */
public class MenuPrincipal extends javax.swing.JPanel {
    /**
     * Creates new form MenuPrincipal
     */
    JPanel painelLogin;
    public MenuPrincipal() {
        initComponents();
        lblNovoJogo.setVisible(false);
        lblimagenSair.setVisible(false);
        painelLogin = new PainelLogin();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelMenu = new javax.swing.JPanel();
        lblSair = new javax.swing.JLabel();
        lblimagen = new javax.swing.JLabel();
        lblimagenSair = new javax.swing.JLabel();
        lblNovoJogo = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1300, 700));
        setLayout(new java.awt.CardLayout());

        JPanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSairMouseExited(evt);
            }
        });
        JPanelMenu.add(lblSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 590, 130, 140));

        lblimagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblimagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimagenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblimagenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblimagenMouseExited(evt);
            }
        });
        JPanelMenu.add(lblimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 280, 130));

        lblimagenSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensMP/lblSair.png"))); // NOI18N
        JPanelMenu.add(lblimagenSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 532, 170, 200));

        lblNovoJogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensMP/btnNovoJogo.png"))); // NOI18N
        JPanelMenu.add(lblNovoJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 393, -1, 230));

        lblFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensMP/TelaFundoN2.jpg"))); // NOI18N
        lblFundo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        JPanelMenu.add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        add(JPanelMenu, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void lblimagenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimagenMouseEntered
        lblNovoJogo.setVisible(true);
    }//GEN-LAST:event_lblimagenMouseEntered

    private void lblimagenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimagenMouseExited
        lblNovoJogo.setVisible(false);
    }//GEN-LAST:event_lblimagenMouseExited

    private void lblSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseEntered
        lblimagenSair.setVisible(true);
    }//GEN-LAST:event_lblSairMouseEntered

    private void lblSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseExited
        lblimagenSair.setVisible(false);
    }//GEN-LAST:event_lblSairMouseExited

    private void lblimagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimagenMouseClicked
       this.add(painelLogin);
       painelLogin.setVisible(true);
       JPanelMenu.setVisible(false);
    }//GEN-LAST:event_lblimagenMouseClicked

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        MenuPrincipal.super.setVisible(false);
    }//GEN-LAST:event_lblSairMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelMenu;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblNovoJogo;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblimagen;
    private javax.swing.JLabel lblimagenSair;
    // End of variables declaration//GEN-END:variables
}
