/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Classes.Jogador;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Isaelsantos
 */
public class PainelLogin extends javax.swing.JPanel {
JPanel painelNovoJogador;
JPanel panelNiveis;


/**
     * Creates new form PainelJogador
     */
    public PainelLogin() {
        initComponents();
        panelNiveis= new TelaNiveis();
        painelNovoJogador = new PainelNovoJogador();
    }
   
private Jogador validarUsuario(String jogador){
    for(int i=0;i<PainelNovoJogador.Usuario.size();i++){
        Jogador usuario = PainelNovoJogador.Usuario.get(i);
        String user = usuario.getUsuario();
        if(user.equals(jogador)){
            return usuario;
        }
    }
    return null;
}

private boolean validarSenha(Jogador jogador){
    String senhaUser = jogador.getSenha();
    String senha1=new String(senha.getPassword()).trim();
    if(validarUsuario(txtLogin.getText())!=null){
        if(senhaUser.equals(senha1)){
            return true;
        }
    }
            JOptionPane.showMessageDialog(null,"Senha Incorreta \n Tente Novamente","Senha incorreta",0);
            senha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            
            return false;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelLogin = new javax.swing.JPanel();
        lblEntrar = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        lblNovoJogador = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        lblFundo = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        PainelLogin.setMinimumSize(new java.awt.Dimension(350, 300));
        PainelLogin.setPreferredSize(new java.awt.Dimension(340, 330));
        PainelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEntrarMouseExited(evt);
            }
        });
        PainelLogin.add(lblEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 180, 60));

        lblSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSairMouseExited(evt);
            }
        });
        PainelLogin.add(lblSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 30, 130, 70));

        lblNovoJogador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNovoJogador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNovoJogadorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNovoJogadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNovoJogadorMouseExited(evt);
            }
        });
        PainelLogin.add(lblNovoJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 340, 60));

        txtLogin.setBackground(new java.awt.Color(0, 0, 0));
        txtLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(255, 255, 255));
        PainelLogin.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 390, 60));

        senha.setBackground(new java.awt.Color(0, 0, 0));
        senha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        senha.setForeground(new java.awt.Color(255, 255, 255));
        senha.setFocusAccelerator('\u0010');
        PainelLogin.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 445, 390, 60));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenslogin/Tela_De_Login_SI01.png"))); // NOI18N
        PainelLogin.add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        add(PainelLogin, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
    System.exit(0);
    }//GEN-LAST:event_lblSairMouseClicked

    private void lblSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseEntered
       lblSair.setIcon(new ImageIcon("src/imagenslogin/btnSair.png"));
    }//GEN-LAST:event_lblSairMouseEntered

    private void lblSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseExited
       lblSair.setIcon(new ImageIcon(""));
    }//GEN-LAST:event_lblSairMouseExited

    private void lblEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarMouseClicked
               if(validarUsuario(txtLogin.getText())!=null){
            if(validarSenha(validarUsuario(txtLogin.getText()))){
                
                Jogador.jogadorAtual=validarUsuario(txtLogin.getText());
                System.out.println(Jogador.jogadorAtual);
                    this.add(panelNiveis);
                    panelNiveis.setVisible(true);
                    PainelLogin.setVisible(false);
            }

        }else{  
            JOptionPane.showMessageDialog(null,"Usuario não encontado \n Tente Novamente","Usuario Não Encontrado",0);
            txtLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
            
        }
    }//GEN-LAST:event_lblEntrarMouseClicked

    private void lblEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarMouseEntered
     lblEntrar.setIcon(new ImageIcon("src/imagenslogin/btnEntrar.png"));
    }//GEN-LAST:event_lblEntrarMouseEntered

    private void lblEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarMouseExited
     lblEntrar.setIcon(new ImageIcon(""));
    }//GEN-LAST:event_lblEntrarMouseExited

    private void lblNovoJogadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovoJogadorMouseExited
        lblNovoJogador.setIcon(new ImageIcon(""));
    }//GEN-LAST:event_lblNovoJogadorMouseExited

    private void lblNovoJogadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovoJogadorMouseEntered
        lblNovoJogador.setIcon(new ImageIcon("src/imagenslogin/btnNovoJogador.png"));
    }//GEN-LAST:event_lblNovoJogadorMouseEntered

    private void lblNovoJogadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNovoJogadorMouseClicked
        this.add(painelNovoJogador);
        painelNovoJogador.setVisible(true);
        PainelLogin.setVisible(false);
    }//GEN-LAST:event_lblNovoJogadorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelLogin;
    private javax.swing.JLabel lblEntrar;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblNovoJogador;
    private javax.swing.JLabel lblSair;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
