/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Classes.Jogador;
import Classes.Recorde;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Instituto Bourbon
 */
public class PainelNovoJogador extends javax.swing.JPanel {

    /**
     * Creates new form PainelNovoJogador
     */
public static ArrayList<Jogador> Usuario = new ArrayList();
    public PainelNovoJogador() {
        initComponents();
            
    }
JPanel painelLogin;
Jogador a;
private boolean validarSenha(String s1,String s2){
    if(s1.length()<=3){
        JOptionPane.showMessageDialog(null,"A senha tem que ter pelo menos 4 digitos","Senha muito facil",2);
        Senha2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        Senha1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        return false;
    }
    else if(!s1.equals(s2)){
        JOptionPane.showMessageDialog(null,"As senhas não são iguais \n Tente novamente","Senhas Diferentes",0);
        Senha2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        Senha1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        return false;
    }
    else{
        Senha2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Senha1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        return true;
    }
    
}
private void adicionar(String usuario,String senha1,String senha2){
    Jogador novoJogador = new Jogador(usuario, senha1, senha2);
    novoJogador.setNivel(1);
    if(BuscaUsuario(novoJogador.getUsuario())){
    JOptionPane.showMessageDialog(null,"Nome de usuario já existe \n Tente Novamente","Usuario já existe",0);
    }else{
        Usuario.add(novoJogador);
        novoJogador=null;
        painelLogin = new PainelLogin();
        this.add(painelLogin);
        painelLogin.setVisible(true);
        PainelNovoJogador.setVisible(false);
    }
}

public ArrayList<Jogador> getArray(){
    return Usuario;
}

private boolean BuscaUsuario(String jogador){
    for(int i=0;i<Usuario.size();i++){
        a = Usuario.get(i);
        String user = a.getUsuario();
        if(user.equals(jogador)){
            return true;
        }
    }
    return false;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelNovoJogador = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        Senha2 = new javax.swing.JPasswordField();
        Senha1 = new javax.swing.JPasswordField();
        lblVoltar = new javax.swing.JLabel();
        lblCriar = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        PainelNovoJogador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        PainelNovoJogador.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 320, 53));

        Senha2.setBackground(new java.awt.Color(0, 0, 0));
        Senha2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Senha2.setForeground(new java.awt.Color(255, 255, 255));
        PainelNovoJogador.add(Senha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 320, 53));

        Senha1.setBackground(new java.awt.Color(0, 0, 0));
        Senha1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Senha1.setForeground(new java.awt.Color(255, 255, 255));
        PainelNovoJogador.add(Senha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 418, 320, 53));

        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVoltarMouseExited(evt);
            }
        });
        PainelNovoJogador.add(lblVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 630, 180, 60));

        lblCriar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCriarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCriarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCriarMouseExited(evt);
            }
        });
        PainelNovoJogador.add(lblCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 630, 140, 60));
        PainelNovoJogador.add(lblSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, 60));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensMP/Tela_De_Register_SI01.png"))); // NOI18N
        PainelNovoJogador.add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        add(PainelNovoJogador, "card2");

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        painelLogin = new PainelLogin();
        this.add(painelLogin);
        painelLogin.setVisible(true);
        PainelNovoJogador.setVisible(false);
    }//GEN-LAST:event_lblVoltarMouseClicked

    private void lblCriarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCriarMouseClicked
        String s1=new String(Senha1.getPassword()).trim();
        String s2=new String(Senha2.getPassword()).trim();
        if(validarSenha(s1,s2)){
           adicionar(txtUsuario.getText(),s1,s2);
        }
    }//GEN-LAST:event_lblCriarMouseClicked

    private void lblCriarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCriarMouseEntered
        lblCriar.setIcon(new ImageIcon("src/imagenslogin/btnCriar.PNG"));
    }//GEN-LAST:event_lblCriarMouseEntered

    private void lblCriarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCriarMouseExited
        lblCriar.setIcon(new ImageIcon(""));
    }//GEN-LAST:event_lblCriarMouseExited

    private void lblVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseEntered
        lblVoltar.setIcon(new ImageIcon("src/imagenslogin/btnVoltar.PNG"));
    }//GEN-LAST:event_lblVoltarMouseEntered

    private void lblVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseExited
        lblCriar.setIcon(new ImageIcon(""));
    }//GEN-LAST:event_lblVoltarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelNovoJogador;
    private javax.swing.JPasswordField Senha1;
    private javax.swing.JPasswordField Senha2;
    private javax.swing.JLabel lblCriar;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblSair;
    private javax.swing.JLabel lblVoltar;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
