/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Niveis;

import Classes.Jogador;
import static Classes.Jogador.jogadorAtual;
import Classes.Recorde;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author isael
 */

public class JogoNivel2 extends javax.swing.JPanel {

    /**
     * Creates new form JogoNivel2
     */
    public JogoNivel2() {
        initComponents();
            iniciarContagem();//Aqui inicia a contagem
            jPanelPausa.setVisible(false);
            panel.setVisible(false);
            setTimer();
            
    }
    JogoNivel1 nivel1;
    private Timer timer;  
    private int currentSegundo = 30;
    private int currentMinuto = 1;
    private int velocidade = 1000;
    String encaixeAtual;
    String pecaAtual;
    String iconeAtual;
    JPanel jogoNivel3;
    JPanel telaNiveis;
Classes.Peca peca = new Classes.Peca();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        panelCronometro = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblTempo = new javax.swing.JLabel();
        lblMelhorTempo = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        lblDicaStart = new javax.swing.JLabel();
        lblReiniciar = new javax.swing.JLabel();
        lblNiveis = new javax.swing.JLabel();
        lblPausar = new javax.swing.JLabel();
        lblFundoCronometro = new javax.swing.JLabel();
        JPanelJogo = new javax.swing.JPanel();
        peca1 = new javax.swing.JLabel();
        peca2 = new javax.swing.JLabel();
        peca3 = new javax.swing.JLabel();
        peca4 = new javax.swing.JLabel();
        peca5 = new javax.swing.JLabel();
        peca6 = new javax.swing.JLabel();
        peca7 = new javax.swing.JLabel();
        peca8 = new javax.swing.JLabel();
        peca9 = new javax.swing.JLabel();
        peca10 = new javax.swing.JLabel();
        peca11 = new javax.swing.JLabel();
        peca12 = new javax.swing.JLabel();
        peca13 = new javax.swing.JLabel();
        peca14 = new javax.swing.JLabel();
        peca15 = new javax.swing.JLabel();
        peca16 = new javax.swing.JLabel();
        encaixe1 = new javax.swing.JLabel();
        encaixe2 = new javax.swing.JLabel();
        encaixe3 = new javax.swing.JLabel();
        encaixe4 = new javax.swing.JLabel();
        encaixe5 = new javax.swing.JLabel();
        encaixe6 = new javax.swing.JLabel();
        encaixe7 = new javax.swing.JLabel();
        encaixe8 = new javax.swing.JLabel();
        encaixe9 = new javax.swing.JLabel();
        encaixe10 = new javax.swing.JLabel();
        encaixe11 = new javax.swing.JLabel();
        encaixe12 = new javax.swing.JLabel();
        encaixe13 = new javax.swing.JLabel();
        encaixe14 = new javax.swing.JLabel();
        encaixe15 = new javax.swing.JLabel();
        encaixe16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        lblDica = new javax.swing.JLabel();
        lblFundoN2 = new javax.swing.JLabel();
        jPanelPausa = new javax.swing.JPanel();
        lblRetomar = new javax.swing.JLabel();
        lblPausa = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCronometro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCronometro.setPreferredSize(new java.awt.Dimension(195, 117));
        panelCronometro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("------");
        lblUser.setName("----------"); // NOI18N
        panelCronometro.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 70, 20));

        lblTempo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTempo.setForeground(new java.awt.Color(255, 255, 255));
        lblTempo.setText("--:--");
        panelCronometro.add(lblTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 85, 50, 20));

        lblMelhorTempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbtn/melhorTempo.png"))); // NOI18N
        panelCronometro.add(lblMelhorTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 170, 110));

        label.setFont(new java.awt.Font("Arial", 1, 45)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("00:00");
        label.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelCronometro.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 60));

        lblDicaStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbtn/btnDica2.png"))); // NOI18N
        lblDicaStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDicaStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDicaStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDicaStartMouseExited(evt);
            }
        });
        panelCronometro.add(lblDicaStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 90, 90));

        lblReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbtn/btnReiniciar.png"))); // NOI18N
        lblReiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReiniciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReiniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReiniciarMouseExited(evt);
            }
        });
        panelCronometro.add(lblReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 120, 50));

        lblNiveis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbtn/btnNiveis.png"))); // NOI18N
        lblNiveis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNiveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNiveisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNiveisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNiveisMouseExited(evt);
            }
        });
        panelCronometro.add(lblNiveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 120, 50));

        lblPausar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbtn/btnPausar.png"))); // NOI18N
        lblPausar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPausar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPausarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPausarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPausarMouseExited(evt);
            }
        });
        panelCronometro.add(lblPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 50));

        lblFundoCronometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/telaCronometroN2.png"))); // NOI18N
        panelCronometro.add(lblFundoCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 180));

        jPanelPrincipal.add(panelCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 1260, 180));

        JPanelJogo.setAutoscrolls(true);
        JPanelJogo.setMinimumSize(new java.awt.Dimension(1240, 700));
        JPanelJogo.setPreferredSize(new java.awt.Dimension(1400, 700));
        JPanelJogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        peca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca1N2.jpg"))); // NOI18N
        peca1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca1MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 150, 100));

        peca2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca2N2.jpg"))); // NOI18N
        peca2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca2MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 150, 100));

        peca3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca3N2.jpg"))); // NOI18N
        peca3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca3MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 150, 100));

        peca4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca4N2.jpg"))); // NOI18N
        peca4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca4MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 100));

        peca5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca5N2.jpg"))); // NOI18N
        peca5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca5MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 100));

        peca6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca6N2.jpg"))); // NOI18N
        peca6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca6MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 150, 100));

        peca7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca7N2.jpg"))); // NOI18N
        peca7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca7MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 150, 100));

        peca8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca8N2.jpg"))); // NOI18N
        peca8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca8MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 150, 100));

        peca9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca9N2.jpg"))); // NOI18N
        peca9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca9MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 150, 100));

        peca10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca10N2.jpg"))); // NOI18N
        peca10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca10MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 150, 100));

        peca11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca11N2.jpg"))); // NOI18N
        peca11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca11MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 100));

        peca12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca12N2.jpg"))); // NOI18N
        peca12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca12MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 150, 100));

        peca13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca13N2.jpg"))); // NOI18N
        peca13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca13MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 150, 100));

        peca14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca14N2.jpg"))); // NOI18N
        peca14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca14MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 150, 100));

        peca15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca15N2.jpg"))); // NOI18N
        peca15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca15MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 150, 100));

        peca16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/peca16N2.jpg"))); // NOI18N
        peca16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        peca16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peca16MouseClicked(evt);
            }
        });
        JPanelJogo.add(peca16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 150, 100));

        encaixe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe1.jpg"))); // NOI18N
        encaixe1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe1MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 150, 100));

        encaixe2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe2.jpg"))); // NOI18N
        encaixe2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe2MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 150, 100));

        encaixe3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe3.jpg"))); // NOI18N
        encaixe3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe3MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 150, 100));

        encaixe4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe4.jpg"))); // NOI18N
        encaixe4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe4MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 150, 100));

        encaixe5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe5.jpg"))); // NOI18N
        encaixe5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe5MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 150, 100));

        encaixe6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe6.jpg"))); // NOI18N
        encaixe6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe6MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 150, 100));

        encaixe7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe7.jpg"))); // NOI18N
        encaixe7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe7MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, 150, 100));

        encaixe8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe8.jpg"))); // NOI18N
        encaixe8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe8MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 120, 150, 100));

        encaixe9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe9.jpg"))); // NOI18N
        encaixe9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe9MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 150, 100));

        encaixe10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe10.jpg"))); // NOI18N
        encaixe10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe10MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 150, 100));

        encaixe11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe11.jpg"))); // NOI18N
        encaixe11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe11MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe11, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, 150, 100));

        encaixe12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe12.jpg"))); // NOI18N
        encaixe12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe12MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 220, 150, 100));

        encaixe13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe13.jpg"))); // NOI18N
        encaixe13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe13MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 150, 100));

        encaixe14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe14.jpg"))); // NOI18N
        encaixe14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe14MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 150, 100));

        encaixe15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe15.jpg"))); // NOI18N
        encaixe15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe15MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe15, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 150, 100));

        encaixe16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/encaixe16.jpg"))); // NOI18N
        encaixe16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        encaixe16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encaixe16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encaixe16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encaixe16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encaixe16MouseExited(evt);
            }
        });
        JPanelJogo.add(encaixe16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 320, 150, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/telaFundoN2.png"))); // NOI18N
        JPanelJogo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 430));

        jPanelPrincipal.add(JPanelJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 430));

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/Top-20-Animes-Dragon-Ball.jpg"))); // NOI18N
        panel.add(lblDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        lblFundoN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/telaFundoN2.png"))); // NOI18N
        panel.add(lblFundoN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 430));

        jPanelPrincipal.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 440));

        jPanelPausa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRetomar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRetomar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRetomarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRetomarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRetomarMouseExited(evt);
            }
        });
        jPanelPausa.add(lblRetomar, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 361, 320, 70));

        lblPausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensN2/telaPausaN2.PNG"))); // NOI18N
        jPanelPausa.add(lblPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        jPanelPrincipal.add(jPanelPausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(jPanelPrincipal, "card5");
    }// </editor-fold>//GEN-END:initComponents

    private void peca1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca1MouseClicked

            pecaAtual="src/imagensN2/peca1N2.jpg";
            iconeAtual =peca.testando(peca1);
       
    }//GEN-LAST:event_peca1MouseClicked

    private void peca2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca2MouseClicked

            pecaAtual="src/imagensN2/peca2N2.jpg";
            iconeAtual =peca.testando(peca2);
        
    }//GEN-LAST:event_peca2MouseClicked

    private void peca3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca3MouseClicked

            pecaAtual="src/imagensN2/peca3N2.jpg";
            iconeAtual =peca.testando(peca3);
        
    }//GEN-LAST:event_peca3MouseClicked

    private void peca4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca4MouseClicked

            pecaAtual="src/imagensN2/peca4N2.jpg";
            iconeAtual =peca.testando(peca4);
        
    }//GEN-LAST:event_peca4MouseClicked

    private void peca5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca5MouseClicked

            pecaAtual="src/imagensN2/peca5N2.jpg";
            iconeAtual =peca.testando(peca5);
        
    }//GEN-LAST:event_peca5MouseClicked

    private void peca6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca6MouseClicked

            pecaAtual="src/imagensN2/peca6N2.jpg";
            iconeAtual =peca.testando(peca6);
        
    }//GEN-LAST:event_peca6MouseClicked

    private void peca7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca7MouseClicked
    
            pecaAtual="src/imagensN2/peca7N2.jpg";
            iconeAtual =peca.testando(peca7);
        
    }//GEN-LAST:event_peca7MouseClicked

    private void peca8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca8MouseClicked

            pecaAtual="src/imagensN2/peca8N2.jpg";
            iconeAtual =peca.testando(peca8);
        
    }//GEN-LAST:event_peca8MouseClicked

    private void peca9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca9MouseClicked

            pecaAtual="src/imagensN2/peca9N2.jpg";
            iconeAtual =peca.testando(peca9);
        
    }//GEN-LAST:event_peca9MouseClicked

    private void peca10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca10MouseClicked

            pecaAtual="src/imagensN2/peca10N2.jpg";
            iconeAtual =peca.testando(peca10);
        
    }//GEN-LAST:event_peca10MouseClicked

    private void peca11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca11MouseClicked

            pecaAtual="src/imagensN2/peca11N2.jpg";
            iconeAtual =peca.testando(peca11);
        
    }//GEN-LAST:event_peca11MouseClicked

    private void peca12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca12MouseClicked

            pecaAtual="src/imagensN2/peca12N2.jpg";
            iconeAtual =peca.testando(peca12);
        
    }//GEN-LAST:event_peca12MouseClicked

    private void peca13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca13MouseClicked

            pecaAtual="src/imagensN2/peca13N2.jpg";
            iconeAtual =peca.testando(peca13);
        
    }//GEN-LAST:event_peca13MouseClicked

    private void peca14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca14MouseClicked

            pecaAtual="src/imagensN2/peca14N2.jpg";
            iconeAtual =peca.testando(peca14);
        
    }//GEN-LAST:event_peca14MouseClicked

    private void peca15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca15MouseClicked
   
        pecaAtual="src/imagensN2/peca15N2.jpg";
        iconeAtual =peca.testando(peca15);
     
    }//GEN-LAST:event_peca15MouseClicked

    private void peca16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peca16MouseClicked

            pecaAtual="src/imagensN2/peca16N2.jpg";
            iconeAtual =peca.testando(peca16);
        
    }//GEN-LAST:event_peca16MouseClicked

    private void encaixe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe1MouseClicked
        encaixeAtual =peca.testando(encaixe1);
        verificacao(this.encaixe1);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe1MouseClicked

    private void encaixe2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe2MouseClicked
        encaixeAtual =peca.testando(encaixe2);
        verificacao(this.encaixe2);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe2MouseClicked

    private void encaixe3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe3MouseClicked
        encaixeAtual =peca.testando(encaixe3);
        verificacao(this.encaixe3);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe3MouseClicked

    private void encaixe4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe4MouseClicked
        encaixeAtual =peca.testando(encaixe4);
        verificacao(this.encaixe4);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe4MouseClicked

    private void encaixe5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe5MouseClicked
        encaixeAtual =peca.testando(encaixe5);
        verificacao(this.encaixe5);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe5MouseClicked

    private void encaixe6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe6MouseClicked
        encaixeAtual =peca.testando(encaixe6);
        verificacao(this.encaixe6);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe6MouseClicked

    private void encaixe7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe7MouseClicked
        encaixeAtual =peca.testando(encaixe7);
        verificacao(this.encaixe7);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe7MouseClicked

    private void encaixe8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe8MouseClicked
         encaixeAtual =peca.testando(encaixe8);
        verificacao(this.encaixe8);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe8MouseClicked

    private void encaixe9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe9MouseClicked
        encaixeAtual =peca.testando(encaixe9);
        verificacao(this.encaixe9);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe9MouseClicked

    private void encaixe10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe10MouseClicked
        encaixeAtual =peca.testando(encaixe10);
        verificacao(this.encaixe10);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe10MouseClicked

    private void encaixe11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe11MouseClicked
        encaixeAtual =peca.testando(encaixe11);
        verificacao(this.encaixe11);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe11MouseClicked

    private void encaixe12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe12MouseClicked
        encaixeAtual =peca.testando(encaixe12);
        verificacao(this.encaixe12);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe12MouseClicked

    private void encaixe13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe13MouseClicked
        encaixeAtual =peca.testando(encaixe13);
        verificacao(this.encaixe13);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe13MouseClicked

    private void encaixe14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe14MouseClicked
        encaixeAtual =peca.testando(encaixe14);
        verificacao(this.encaixe14);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe14MouseClicked

    private void encaixe15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe15MouseClicked
        encaixeAtual =peca.testando(encaixe15);
        verificacao(this.encaixe15);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe15MouseClicked

    private void encaixe16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe16MouseClicked
        encaixeAtual =peca.testando(encaixe16);
        verificacao(this.encaixe16);
        tiraricone();
        vereficarIconesNV2();
    }//GEN-LAST:event_encaixe16MouseClicked

    private void encaixe1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe1MouseEntered
peca.getBorda(encaixe1);
    }//GEN-LAST:event_encaixe1MouseEntered

    private void encaixe1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe1MouseExited
peca.setBorda(encaixe1);
    }//GEN-LAST:event_encaixe1MouseExited

    private void encaixe2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe2MouseEntered
peca.getBorda(encaixe2);
    }//GEN-LAST:event_encaixe2MouseEntered

    private void encaixe2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe2MouseExited
peca.setBorda(encaixe2);
    }//GEN-LAST:event_encaixe2MouseExited

    private void encaixe3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe3MouseEntered
peca.getBorda(encaixe3);
    }//GEN-LAST:event_encaixe3MouseEntered

    private void encaixe3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe3MouseExited
 peca.setBorda(encaixe3);
    }//GEN-LAST:event_encaixe3MouseExited

    private void encaixe4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe4MouseEntered
peca.getBorda(encaixe4);
    }//GEN-LAST:event_encaixe4MouseEntered

    private void encaixe4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe4MouseExited
peca.setBorda(encaixe4);
    }//GEN-LAST:event_encaixe4MouseExited

    private void encaixe5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe5MouseEntered
peca.getBorda(encaixe5);
    }//GEN-LAST:event_encaixe5MouseEntered

    private void encaixe5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe5MouseExited
peca.setBorda(encaixe5);
    }//GEN-LAST:event_encaixe5MouseExited

    private void encaixe6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe6MouseEntered
peca.getBorda(encaixe6);
    }//GEN-LAST:event_encaixe6MouseEntered

    private void encaixe6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe6MouseExited
peca.setBorda(encaixe6);
    }//GEN-LAST:event_encaixe6MouseExited

    private void encaixe7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe7MouseEntered
peca.getBorda(encaixe7);
    }//GEN-LAST:event_encaixe7MouseEntered

    private void encaixe7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe7MouseExited
peca.setBorda(encaixe7);
    }//GEN-LAST:event_encaixe7MouseExited

    private void encaixe8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe8MouseEntered
peca.getBorda(encaixe8);
    }//GEN-LAST:event_encaixe8MouseEntered

    private void encaixe8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe8MouseExited
peca.setBorda(encaixe8);
    }//GEN-LAST:event_encaixe8MouseExited

    private void encaixe9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe9MouseEntered
peca.getBorda(encaixe9);
    }//GEN-LAST:event_encaixe9MouseEntered

    private void encaixe9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe9MouseExited
peca.setBorda(encaixe9);
    }//GEN-LAST:event_encaixe9MouseExited

    private void encaixe10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe10MouseEntered
peca.getBorda(encaixe10);
    }//GEN-LAST:event_encaixe10MouseEntered

    private void encaixe10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe10MouseExited
peca.setBorda(encaixe10);
    }//GEN-LAST:event_encaixe10MouseExited

    private void encaixe11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe11MouseEntered
peca.getBorda(encaixe11);    }//GEN-LAST:event_encaixe11MouseEntered

    private void encaixe11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe11MouseExited
peca.setBorda(encaixe11);    }//GEN-LAST:event_encaixe11MouseExited

    private void encaixe12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe12MouseEntered
peca.getBorda(encaixe12);    }//GEN-LAST:event_encaixe12MouseEntered

    private void encaixe12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe12MouseExited
peca.setBorda(encaixe12);    }//GEN-LAST:event_encaixe12MouseExited

    private void encaixe13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe13MouseEntered
peca.getBorda(encaixe13);    }//GEN-LAST:event_encaixe13MouseEntered

    private void encaixe13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe13MouseExited
peca.setBorda(encaixe13);    }//GEN-LAST:event_encaixe13MouseExited

    private void encaixe14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe14MouseEntered
peca.getBorda(encaixe14);    }//GEN-LAST:event_encaixe14MouseEntered

    private void encaixe14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe14MouseExited
peca.setBorda(encaixe14);    }//GEN-LAST:event_encaixe14MouseExited

    private void encaixe15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe15MouseEntered
peca.getBorda(encaixe15);    }//GEN-LAST:event_encaixe15MouseEntered

    private void encaixe15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe15MouseExited
  peca.setBorda(encaixe15);
    }//GEN-LAST:event_encaixe15MouseExited

    private void encaixe16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe16MouseEntered
peca.getBorda(encaixe16);    }//GEN-LAST:event_encaixe16MouseEntered

    private void encaixe16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encaixe16MouseExited
peca.setBorda(encaixe16);    }//GEN-LAST:event_encaixe16MouseExited

    private void lblDicaStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDicaStartMouseEntered
        lblDicaStart.setIcon(new ImageIcon("src/imagensbtn/btnDica.png"));
        if(currentSegundo>10){
            currentSegundo +=-5;
        }
        JPanelJogo.setVisible(false);
        panel.setVisible(true);
    }//GEN-LAST:event_lblDicaStartMouseEntered

    private void lblDicaStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDicaStartMouseExited
        lblDicaStart.setIcon(new ImageIcon("src/imagensbtn/btnDica2.png"));
        panel.setVisible(false);
        JPanelJogo.setVisible(true);
    }//GEN-LAST:event_lblDicaStartMouseExited

    private void lblReiniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReiniciarMouseClicked
        reinicia();
        stopTime();
        timer.restart();
    }//GEN-LAST:event_lblReiniciarMouseClicked

    private void lblReiniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReiniciarMouseEntered
        lblReiniciar.setIcon(new ImageIcon("src/imagensbtn/btnReiniciar2.png"));
    }//GEN-LAST:event_lblReiniciarMouseEntered

    private void lblReiniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReiniciarMouseExited
        lblReiniciar.setIcon(new ImageIcon("src/imagensbtn/btnReiniciar.png"));
    }//GEN-LAST:event_lblReiniciarMouseExited

    private void lblNiveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNiveisMouseClicked
        stopTime();
        super.setVisible(false);
    }//GEN-LAST:event_lblNiveisMouseClicked

    private void lblNiveisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNiveisMouseEntered
        lblNiveis.setIcon(new ImageIcon("src/imagensbtn/btnNiveis2.png"));
    }//GEN-LAST:event_lblNiveisMouseEntered

    private void lblNiveisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNiveisMouseExited
        lblNiveis.setIcon(new ImageIcon("src/imagensbtn/btnNiveis.png"));
    }//GEN-LAST:event_lblNiveisMouseExited

    private void lblPausarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPausarMouseClicked
        timer.stop();
        panelCronometro.setVisible(false);
        JPanelJogo.setVisible(false);
        jPanelPausa.setVisible(true);
    }//GEN-LAST:event_lblPausarMouseClicked

    private void lblPausarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPausarMouseEntered
        lblPausar.setIcon(new ImageIcon("src/imagensbtn/btnPausar2.png"));
    }//GEN-LAST:event_lblPausarMouseEntered

    private void lblPausarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPausarMouseExited
        lblPausar.setIcon(new ImageIcon("src/imagensbtn/btnPausar.png"));
    }//GEN-LAST:event_lblPausarMouseExited

    private void lblRetomarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetomarMouseEntered
        lblRetomar.setIcon(new ImageIcon("src/imagensN2/btnRetomarN2.png"));
    }//GEN-LAST:event_lblRetomarMouseEntered

    private void lblRetomarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetomarMouseExited
        lblRetomar.setIcon(new ImageIcon(""));
    }//GEN-LAST:event_lblRetomarMouseExited

    private void lblRetomarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetomarMouseClicked
         jPanelPausa.setVisible(false);
        JPanelJogo.setVisible(true);
        panelCronometro.setVisible(true);
        timer.restart();
    }//GEN-LAST:event_lblRetomarMouseClicked



    
  /*
  *Esta funçao e reponsavel por retirar o icone que foi encaixado no jogo
  */
    
    private void vereficaRecorde(){
       int minuto = currentMinuto * 60;
       int segundos = currentSegundo;
       int rec = 90-(minuto + segundos);
       jogadorAtual.settempo2(90-rec);
       Recorde.recorde.novoRecord2(rec, jogadorAtual.getUsuario());
       if(Recorde.recorde.getRecordeNivel2()>0){
           setTimer();
        }
    }
    
    private void setTimer(){
        lblTempo.setText(Integer.toString(Recorde.recorde.getRecordeNivel2()));
        lblUser.setText(Recorde.nomeRecorde2);
    }
    private void tiraricone(){
        if(iconeAtual!=null){
        peca.tiraIcone(iconeAtual,peca1);
        peca.tiraIcone(iconeAtual,peca2);
        peca.tiraIcone(iconeAtual,peca3);
        peca.tiraIcone(iconeAtual,peca4);
        peca.tiraIcone(iconeAtual,peca5);
        peca.tiraIcone(iconeAtual,peca6);
        peca.tiraIcone(iconeAtual,peca7);
        peca.tiraIcone(iconeAtual,peca8);
        peca.tiraIcone(iconeAtual,peca9);
        peca.tiraIcone(iconeAtual,peca10);
        peca.tiraIcone(iconeAtual,peca11);
        peca.tiraIcone(iconeAtual,peca12);
        peca.tiraIcone(iconeAtual,peca13);
        peca.tiraIcone(iconeAtual,peca14);
        peca.tiraIcone(iconeAtual,peca15);
        peca.tiraIcone(iconeAtual,peca16);}
        
        
    }
  private void reinicia(){
        peca.reiniciar(encaixe1,peca1,2,1);      
        peca.reiniciar(encaixe2,peca2,2,2);      
        peca.reiniciar(encaixe3,peca3,2,3);      
        peca.reiniciar(encaixe4,peca4,2,4);      
        peca.reiniciar(encaixe5,peca5,2,5);      
        peca.reiniciar(encaixe6,peca6,2,6);      
        peca.reiniciar(encaixe7,peca7,2,7);      
        peca.reiniciar(encaixe8,peca8,2,8);      
        peca.reiniciar(encaixe9,peca9,2,9);      
        peca.reiniciar(encaixe10,peca10,2,10);      
        peca.reiniciar(encaixe11,peca11,2,11);      
        peca.reiniciar(encaixe12,peca12,2,12);      
        peca.reiniciar(encaixe13,peca13,2,13);      
        peca.reiniciar(encaixe14,peca14,2,14);      
        peca.reiniciar(encaixe15,peca15,2,15);      
        peca.reiniciar(encaixe16,peca16,2,16);
        iconeAtual=null;
  }

/*
 *Essa função verefica se os encaixes Já possue icone e quando e selecionado
 *ele retorna esse icone para possição antiga..
 */
 
    private void executa(){
            peca.retornarIcone(encaixeAtual,peca1);
            peca.retornarIcone(encaixeAtual,peca2);
            peca.retornarIcone(encaixeAtual,peca3);
            peca.retornarIcone(encaixeAtual,peca4);
            peca.retornarIcone(encaixeAtual,peca5);
            peca.retornarIcone(encaixeAtual,peca6);
            peca.retornarIcone(encaixeAtual,peca7);
            peca.retornarIcone(encaixeAtual,peca8);
            peca.retornarIcone(encaixeAtual,peca9);
            peca.retornarIcone(encaixeAtual,peca10);
            peca.retornarIcone(encaixeAtual,peca11);
            peca.retornarIcone(encaixeAtual,peca12);
            peca.retornarIcone(encaixeAtual,peca13);
            peca.retornarIcone(encaixeAtual,peca14);
            peca.retornarIcone(encaixeAtual,peca15);
            peca.retornarIcone(encaixeAtual,peca16);
    
    }
    
    private void verificacao(JLabel encaixe){
            if(pecaAtual==null){JOptionPane.showMessageDialog(null, "Selecione um novo Icone");}
                else{encaixe.setIcon(new ImageIcon(pecaAtual));executa();}
            pecaAtual=null;
    }
    
    private void vereficarIconesNV2(){
        setTimer();
        if(peca.vereficarVencedor(peca1,encaixe1)&&peca.vereficarVencedor(peca2,encaixe2)&&
           peca.vereficarVencedor(peca3,encaixe3)&&peca.vereficarVencedor(peca4,encaixe4)&&
           peca.vereficarVencedor(peca5,encaixe5)&&peca.vereficarVencedor(peca6,encaixe6)&&
           peca.vereficarVencedor(peca7,encaixe7)&&peca.vereficarVencedor(peca8,encaixe8)&&
           peca.vereficarVencedor(peca9,encaixe9)&&peca.vereficarVencedor(peca10,encaixe10)&&
           peca.vereficarVencedor(peca11,encaixe11)&&peca.vereficarVencedor(peca12,encaixe12)&&
           peca.vereficarVencedor(peca13,encaixe13)&&peca.vereficarVencedor(peca14,encaixe14)&&
           peca.vereficarVencedor(peca15,encaixe15)&&peca.vereficarVencedor(peca16,encaixe16)){
            Jogador.jogadorAtual.setNivel(3);
            vereficaRecorde();
            stopTime();
            reinicia();
            int returnValue = 0;
            returnValue = JOptionPane.showConfirmDialog(null, "Parabens Voce Passou\nGostaria de Jogar Novamente?", "Proximo Nivel", JOptionPane.YES_NO_OPTION);
            if (returnValue == JOptionPane.YES_OPTION){
                stopTime();
                timer.restart();
            }else{
                super.setVisible(false);
            }
        }
    }
//INICIA O CRONOMETRO APARTIR DAQUI //
        private void iniciarContagem() {
        ActionListener action = new ActionListener() {  
            public void actionPerformed(ActionEvent e) {  
                currentSegundo--;
                
                if(currentSegundo<=0){
                    currentMinuto--;
                    currentSegundo = 60;
                }
                if(currentMinuto<0){
                    reinicia();
                    stopTime();
                    timer.restart();
                }
                if(currentSegundo<=20 && currentMinuto == 0){
                    label.setBackground(Color.red);
                    label.setForeground(Color.red);
                }else{
                    label.setBackground(Color.white);
                    label.setForeground(Color.white);
                }
                String min = currentMinuto <= 9? "0"+currentMinuto:currentMinuto+"";
                String seg = currentSegundo <= 9? "0"+currentSegundo:currentSegundo+"";
                label.setText(min+":"+seg);  
            }  
        };  
        this.timer = new Timer(velocidade, action);  
        this.timer.start();
    }

    private void stopTime() {
        timer.stop();
        currentMinuto = 1;
        currentSegundo = 30;
        label.setText("01:30");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelJogo;
    private javax.swing.JLabel encaixe1;
    private javax.swing.JLabel encaixe10;
    private javax.swing.JLabel encaixe11;
    private javax.swing.JLabel encaixe12;
    private javax.swing.JLabel encaixe13;
    private javax.swing.JLabel encaixe14;
    private javax.swing.JLabel encaixe15;
    private javax.swing.JLabel encaixe16;
    private javax.swing.JLabel encaixe2;
    private javax.swing.JLabel encaixe3;
    private javax.swing.JLabel encaixe4;
    private javax.swing.JLabel encaixe5;
    private javax.swing.JLabel encaixe6;
    private javax.swing.JLabel encaixe7;
    private javax.swing.JLabel encaixe8;
    private javax.swing.JLabel encaixe9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelPausa;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblDica;
    private javax.swing.JLabel lblDicaStart;
    private javax.swing.JLabel lblFundoCronometro;
    private javax.swing.JLabel lblFundoN2;
    private javax.swing.JLabel lblMelhorTempo;
    private javax.swing.JLabel lblNiveis;
    private javax.swing.JLabel lblPausa;
    private javax.swing.JLabel lblPausar;
    private javax.swing.JLabel lblReiniciar;
    private javax.swing.JLabel lblRetomar;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelCronometro;
    private javax.swing.JLabel peca1;
    private javax.swing.JLabel peca10;
    private javax.swing.JLabel peca11;
    private javax.swing.JLabel peca12;
    private javax.swing.JLabel peca13;
    private javax.swing.JLabel peca14;
    private javax.swing.JLabel peca15;
    private javax.swing.JLabel peca16;
    private javax.swing.JLabel peca2;
    private javax.swing.JLabel peca3;
    private javax.swing.JLabel peca4;
    private javax.swing.JLabel peca5;
    private javax.swing.JLabel peca6;
    private javax.swing.JLabel peca7;
    private javax.swing.JLabel peca8;
    private javax.swing.JLabel peca9;
    // End of variables declaration//GEN-END:variables
}
